site_name: 3RWW SEWER ATLAS
site_description: Help documentation for the 3 Rivers Wet Weather Atlas products.
nav:
- Overview: index.md
- Documentation:
    - Contents: help_rsi.md
    - Interface:  help_rsi_ui.md
    - Common Tasks:  help_rsi_tasks.md
- Guides:
    - Discharge Analysis: guide_rsi_trace.md
- Data:
    - Downloads and Services: services_and_downloads.md
    - Data Release Change Log: changelog.md
    - Data Versioning Primer: semver.md    
markdown_extensions:
    - smarty
site_dir:
    D:\Dropbox (CivicMapper)\Projects\3RWW\projects\docs\atlas_mkdocs_build\
extra_css:
    - extra.css